#practica_01 luigy septiembre 2014
CC=g++
CCFLAGS=-c -Wall -o

ejecutable:  main
#lista
	$(CC) -o practica main.o 
#practica lista_simple.o

main:
	$(CC) $(CCFLAGS) main.o main.cpp

#lista:
#	$(CC) $(CCFLAGS) lista_simple.o lista_simple.cpp

clean:
	rm -rf *o practica
